### PR TITLE
Updates addon to be compatible with Fastboot 1.0.0 +

### PR DESCRIPTION
**Pull request by linearza**

### CODE REVIEW

**Comment by alexlafroscia** [comment]
Hey @linearza, thanks for submitting this! Looks great to me, but since we're now using `broccoli-stew` directly, could you add it to the dependencies? It probably works now since it's likely a dependency somewhere in the tree, but it would be better to be explicit about the dependencies I think.

**Comment by linearza** [comment]
Sure thing, updated

**Comment by alexlafroscia** [comment]
Thanks for that! This project uses `yarn` though, do you'll need to do `yarn add -D broccoli-stew` to install it correctly and update the lockfile 😅

**Comment by linearza** [comment]
Aijaijajaijai! :smile: updated

**Comment by alexlafroscia** [comment]
Boom! Thank you 😁

**Comment by alexlafroscia** [comment]
I just cut `v1.0.0` with this change. Felt better to make this a major update since people might have issues with older Fastboot versions now. Better to err on the side of safety with version numbers.

**Comment by linearza** [comment]
Great stuff! Thanks for the addon!

**Comment by alexlafroscia** [comment]
Sure thing 😁  I honestly thought I was the only one using it!

**Pull request merged**
